//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Qa_Payment
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuatarPayemntEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuatarPayemntEntities object using the connection string found in the 'QuatarPayemntEntities' section of the application configuration file.
        /// </summary>
        public QuatarPayemntEntities() : base("name=QuatarPayemntEntities", "QuatarPayemntEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuatarPayemntEntities object.
        /// </summary>
        public QuatarPayemntEntities(string connectionString) : base(connectionString, "QuatarPayemntEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuatarPayemntEntities object.
        /// </summary>
        public QuatarPayemntEntities(EntityConnection connection) : base(connection, "QuatarPayemntEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_CLIENTMASTER> TBLQU_CLIENTMASTER
        {
            get
            {
                if ((_TBLQU_CLIENTMASTER == null))
                {
                    _TBLQU_CLIENTMASTER = base.CreateObjectSet<TBLQU_CLIENTMASTER>("TBLQU_CLIENTMASTER");
                }
                return _TBLQU_CLIENTMASTER;
            }
        }
        private ObjectSet<TBLQU_CLIENTMASTER> _TBLQU_CLIENTMASTER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_PAYMENTRate> TBLQU_PAYMENTRate
        {
            get
            {
                if ((_TBLQU_PAYMENTRate == null))
                {
                    _TBLQU_PAYMENTRate = base.CreateObjectSet<TBLQU_PAYMENTRate>("TBLQU_PAYMENTRate");
                }
                return _TBLQU_PAYMENTRate;
            }
        }
        private ObjectSet<TBLQU_PAYMENTRate> _TBLQU_PAYMENTRate;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_User_Master> TBLQU_User_Master
        {
            get
            {
                if ((_TBLQU_User_Master == null))
                {
                    _TBLQU_User_Master = base.CreateObjectSet<TBLQU_User_Master>("TBLQU_User_Master");
                }
                return _TBLQU_User_Master;
            }
        }
        private ObjectSet<TBLQU_User_Master> _TBLQU_User_Master;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_PAYMENTHIS> TBLQU_PAYMENTHIS
        {
            get
            {
                if ((_TBLQU_PAYMENTHIS == null))
                {
                    _TBLQU_PAYMENTHIS = base.CreateObjectSet<TBLQU_PAYMENTHIS>("TBLQU_PAYMENTHIS");
                }
                return _TBLQU_PAYMENTHIS;
            }
        }
        private ObjectSet<TBLQU_PAYMENTHIS> _TBLQU_PAYMENTHIS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_UserLocation> TBLQU_UserLocation
        {
            get
            {
                if ((_TBLQU_UserLocation == null))
                {
                    _TBLQU_UserLocation = base.CreateObjectSet<TBLQU_UserLocation>("TBLQU_UserLocation");
                }
                return _TBLQU_UserLocation;
            }
        }
        private ObjectSet<TBLQU_UserLocation> _TBLQU_UserLocation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_PAYMENTMASTER> TBLQU_PAYMENTMASTER
        {
            get
            {
                if ((_TBLQU_PAYMENTMASTER == null))
                {
                    _TBLQU_PAYMENTMASTER = base.CreateObjectSet<TBLQU_PAYMENTMASTER>("TBLQU_PAYMENTMASTER");
                }
                return _TBLQU_PAYMENTMASTER;
            }
        }
        private ObjectSet<TBLQU_PAYMENTMASTER> _TBLQU_PAYMENTMASTER;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_CLIENTMASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_CLIENTMASTER(TBLQU_CLIENTMASTER tBLQU_CLIENTMASTER)
        {
            base.AddObject("TBLQU_CLIENTMASTER", tBLQU_CLIENTMASTER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_PAYMENTRate EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_PAYMENTRate(TBLQU_PAYMENTRate tBLQU_PAYMENTRate)
        {
            base.AddObject("TBLQU_PAYMENTRate", tBLQU_PAYMENTRate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_User_Master EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_User_Master(TBLQU_User_Master tBLQU_User_Master)
        {
            base.AddObject("TBLQU_User_Master", tBLQU_User_Master);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_PAYMENTHIS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_PAYMENTHIS(TBLQU_PAYMENTHIS tBLQU_PAYMENTHIS)
        {
            base.AddObject("TBLQU_PAYMENTHIS", tBLQU_PAYMENTHIS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_UserLocation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_UserLocation(TBLQU_UserLocation tBLQU_UserLocation)
        {
            base.AddObject("TBLQU_UserLocation", tBLQU_UserLocation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_PAYMENTMASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_PAYMENTMASTER(TBLQU_PAYMENTMASTER tBLQU_PAYMENTMASTER)
        {
            base.AddObject("TBLQU_PAYMENTMASTER", tBLQU_PAYMENTMASTER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuatarPayemntModel", Name="TBLQU_CLIENTMASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_CLIENTMASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_CLIENTMASTER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="mobileNo">Initial value of the MobileNo property.</param>
        /// <param name="emailID">Initial value of the EmailID property.</param>
        public static TBLQU_CLIENTMASTER CreateTBLQU_CLIENTMASTER(global::System.Int32 id, global::System.String mobileNo, global::System.String emailID)
        {
            TBLQU_CLIENTMASTER tBLQU_CLIENTMASTER = new TBLQU_CLIENTMASTER();
            tBLQU_CLIENTMASTER.ID = id;
            tBLQU_CLIENTMASTER.MobileNo = mobileNo;
            tBLQU_CLIENTMASTER.EmailID = emailID;
            return tBLQU_CLIENTMASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.String _ClientID;
        partial void OnClientIDChanging(global::System.String value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientfirstName
        {
            get
            {
                return _ClientfirstName;
            }
            set
            {
                OnClientfirstNameChanging(value);
                ReportPropertyChanging("ClientfirstName");
                _ClientfirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientfirstName");
                OnClientfirstNameChanged();
            }
        }
        private global::System.String _ClientfirstName;
        partial void OnClientfirstNameChanging(global::System.String value);
        partial void OnClientfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientLastName
        {
            get
            {
                return _ClientLastName;
            }
            set
            {
                OnClientLastNameChanging(value);
                ReportPropertyChanging("ClientLastName");
                _ClientLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientLastName");
                OnClientLastNameChanged();
            }
        }
        private global::System.String _ClientLastName;
        partial void OnClientLastNameChanging(global::System.String value);
        partial void OnClientLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.String _PhoneNo;
        partial void OnPhoneNoChanging(global::System.String value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MobileNo
        {
            get
            {
                return _MobileNo;
            }
            set
            {
                OnMobileNoChanging(value);
                ReportPropertyChanging("MobileNo");
                _MobileNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MobileNo");
                OnMobileNoChanged();
            }
        }
        private global::System.String _MobileNo;
        partial void OnMobileNoChanging(global::System.String value);
        partial void OnMobileNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuatarPayemntModel", Name="TBLQU_PAYMENTHIS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_PAYMENTHIS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_PAYMENTHIS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="vpc_MerchTxnRef">Initial value of the vpc_MerchTxnRef property.</param>
        /// <param name="vpc_TxnResponseCode">Initial value of the vpc_TxnResponseCode property.</param>
        /// <param name="vpc_Amount">Initial value of the vpc_Amount property.</param>
        /// <param name="vpc_Command">Initial value of the vpc_Command property.</param>
        /// <param name="vpc_Version">Initial value of the vpc_Version property.</param>
        /// <param name="vpc_OrderInfo">Initial value of the vpc_OrderInfo property.</param>
        /// <param name="vpc_Merchant">Initial value of the vpc_Merchant property.</param>
        /// <param name="vpc_BatchNo">Initial value of the vpc_BatchNo property.</param>
        /// <param name="vpc_Card">Initial value of the vpc_Card property.</param>
        /// <param name="vpc_ReceiptNo">Initial value of the vpc_ReceiptNo property.</param>
        /// <param name="vpc_AuthorizeId">Initial value of the vpc_AuthorizeId property.</param>
        /// <param name="vpc_AcqResponseCode">Initial value of the vpc_AcqResponseCode property.</param>
        /// <param name="vpc_TransactionNo">Initial value of the vpc_TransactionNo property.</param>
        /// <param name="vpc_Message">Initial value of the vpc_Message property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        /// <param name="modifed_date">Initial value of the modifed_date property.</param>
        public static TBLQU_PAYMENTHIS CreateTBLQU_PAYMENTHIS(global::System.Int32 id, global::System.String vpc_MerchTxnRef, global::System.String vpc_TxnResponseCode, global::System.String vpc_Amount, global::System.String vpc_Command, global::System.String vpc_Version, global::System.String vpc_OrderInfo, global::System.String vpc_Merchant, global::System.String vpc_BatchNo, global::System.String vpc_Card, global::System.String vpc_ReceiptNo, global::System.String vpc_AuthorizeId, global::System.String vpc_AcqResponseCode, global::System.String vpc_TransactionNo, global::System.String vpc_Message, global::System.DateTime created_date, global::System.DateTime modifed_date)
        {
            TBLQU_PAYMENTHIS tBLQU_PAYMENTHIS = new TBLQU_PAYMENTHIS();
            tBLQU_PAYMENTHIS.ID = id;
            tBLQU_PAYMENTHIS.vpc_MerchTxnRef = vpc_MerchTxnRef;
            tBLQU_PAYMENTHIS.vpc_TxnResponseCode = vpc_TxnResponseCode;
            tBLQU_PAYMENTHIS.vpc_Amount = vpc_Amount;
            tBLQU_PAYMENTHIS.vpc_Command = vpc_Command;
            tBLQU_PAYMENTHIS.vpc_Version = vpc_Version;
            tBLQU_PAYMENTHIS.vpc_OrderInfo = vpc_OrderInfo;
            tBLQU_PAYMENTHIS.vpc_Merchant = vpc_Merchant;
            tBLQU_PAYMENTHIS.vpc_BatchNo = vpc_BatchNo;
            tBLQU_PAYMENTHIS.vpc_Card = vpc_Card;
            tBLQU_PAYMENTHIS.vpc_ReceiptNo = vpc_ReceiptNo;
            tBLQU_PAYMENTHIS.vpc_AuthorizeId = vpc_AuthorizeId;
            tBLQU_PAYMENTHIS.vpc_AcqResponseCode = vpc_AcqResponseCode;
            tBLQU_PAYMENTHIS.vpc_TransactionNo = vpc_TransactionNo;
            tBLQU_PAYMENTHIS.vpc_Message = vpc_Message;
            tBLQU_PAYMENTHIS.created_date = created_date;
            tBLQU_PAYMENTHIS.modifed_date = modifed_date;
            return tBLQU_PAYMENTHIS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_MerchTxnRef
        {
            get
            {
                return _vpc_MerchTxnRef;
            }
            set
            {
                Onvpc_MerchTxnRefChanging(value);
                ReportPropertyChanging("vpc_MerchTxnRef");
                _vpc_MerchTxnRef = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_MerchTxnRef");
                Onvpc_MerchTxnRefChanged();
            }
        }
        private global::System.String _vpc_MerchTxnRef;
        partial void Onvpc_MerchTxnRefChanging(global::System.String value);
        partial void Onvpc_MerchTxnRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_TxnResponseCode
        {
            get
            {
                return _vpc_TxnResponseCode;
            }
            set
            {
                Onvpc_TxnResponseCodeChanging(value);
                ReportPropertyChanging("vpc_TxnResponseCode");
                _vpc_TxnResponseCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_TxnResponseCode");
                Onvpc_TxnResponseCodeChanged();
            }
        }
        private global::System.String _vpc_TxnResponseCode;
        partial void Onvpc_TxnResponseCodeChanging(global::System.String value);
        partial void Onvpc_TxnResponseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_Amount
        {
            get
            {
                return _vpc_Amount;
            }
            set
            {
                Onvpc_AmountChanging(value);
                ReportPropertyChanging("vpc_Amount");
                _vpc_Amount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_Amount");
                Onvpc_AmountChanged();
            }
        }
        private global::System.String _vpc_Amount;
        partial void Onvpc_AmountChanging(global::System.String value);
        partial void Onvpc_AmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_Command
        {
            get
            {
                return _vpc_Command;
            }
            set
            {
                Onvpc_CommandChanging(value);
                ReportPropertyChanging("vpc_Command");
                _vpc_Command = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_Command");
                Onvpc_CommandChanged();
            }
        }
        private global::System.String _vpc_Command;
        partial void Onvpc_CommandChanging(global::System.String value);
        partial void Onvpc_CommandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_Version
        {
            get
            {
                return _vpc_Version;
            }
            set
            {
                Onvpc_VersionChanging(value);
                ReportPropertyChanging("vpc_Version");
                _vpc_Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_Version");
                Onvpc_VersionChanged();
            }
        }
        private global::System.String _vpc_Version;
        partial void Onvpc_VersionChanging(global::System.String value);
        partial void Onvpc_VersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_OrderInfo
        {
            get
            {
                return _vpc_OrderInfo;
            }
            set
            {
                Onvpc_OrderInfoChanging(value);
                ReportPropertyChanging("vpc_OrderInfo");
                _vpc_OrderInfo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_OrderInfo");
                Onvpc_OrderInfoChanged();
            }
        }
        private global::System.String _vpc_OrderInfo;
        partial void Onvpc_OrderInfoChanging(global::System.String value);
        partial void Onvpc_OrderInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_Merchant
        {
            get
            {
                return _vpc_Merchant;
            }
            set
            {
                Onvpc_MerchantChanging(value);
                ReportPropertyChanging("vpc_Merchant");
                _vpc_Merchant = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_Merchant");
                Onvpc_MerchantChanged();
            }
        }
        private global::System.String _vpc_Merchant;
        partial void Onvpc_MerchantChanging(global::System.String value);
        partial void Onvpc_MerchantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_BatchNo
        {
            get
            {
                return _vpc_BatchNo;
            }
            set
            {
                Onvpc_BatchNoChanging(value);
                ReportPropertyChanging("vpc_BatchNo");
                _vpc_BatchNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_BatchNo");
                Onvpc_BatchNoChanged();
            }
        }
        private global::System.String _vpc_BatchNo;
        partial void Onvpc_BatchNoChanging(global::System.String value);
        partial void Onvpc_BatchNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_Card
        {
            get
            {
                return _vpc_Card;
            }
            set
            {
                Onvpc_CardChanging(value);
                ReportPropertyChanging("vpc_Card");
                _vpc_Card = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_Card");
                Onvpc_CardChanged();
            }
        }
        private global::System.String _vpc_Card;
        partial void Onvpc_CardChanging(global::System.String value);
        partial void Onvpc_CardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_ReceiptNo
        {
            get
            {
                return _vpc_ReceiptNo;
            }
            set
            {
                Onvpc_ReceiptNoChanging(value);
                ReportPropertyChanging("vpc_ReceiptNo");
                _vpc_ReceiptNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_ReceiptNo");
                Onvpc_ReceiptNoChanged();
            }
        }
        private global::System.String _vpc_ReceiptNo;
        partial void Onvpc_ReceiptNoChanging(global::System.String value);
        partial void Onvpc_ReceiptNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_AuthorizeId
        {
            get
            {
                return _vpc_AuthorizeId;
            }
            set
            {
                Onvpc_AuthorizeIdChanging(value);
                ReportPropertyChanging("vpc_AuthorizeId");
                _vpc_AuthorizeId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_AuthorizeId");
                Onvpc_AuthorizeIdChanged();
            }
        }
        private global::System.String _vpc_AuthorizeId;
        partial void Onvpc_AuthorizeIdChanging(global::System.String value);
        partial void Onvpc_AuthorizeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_AcqResponseCode
        {
            get
            {
                return _vpc_AcqResponseCode;
            }
            set
            {
                Onvpc_AcqResponseCodeChanging(value);
                ReportPropertyChanging("vpc_AcqResponseCode");
                _vpc_AcqResponseCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_AcqResponseCode");
                Onvpc_AcqResponseCodeChanged();
            }
        }
        private global::System.String _vpc_AcqResponseCode;
        partial void Onvpc_AcqResponseCodeChanging(global::System.String value);
        partial void Onvpc_AcqResponseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_TransactionNo
        {
            get
            {
                return _vpc_TransactionNo;
            }
            set
            {
                Onvpc_TransactionNoChanging(value);
                ReportPropertyChanging("vpc_TransactionNo");
                _vpc_TransactionNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_TransactionNo");
                Onvpc_TransactionNoChanged();
            }
        }
        private global::System.String _vpc_TransactionNo;
        partial void Onvpc_TransactionNoChanging(global::System.String value);
        partial void Onvpc_TransactionNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vpc_Message
        {
            get
            {
                return _vpc_Message;
            }
            set
            {
                Onvpc_MessageChanging(value);
                ReportPropertyChanging("vpc_Message");
                _vpc_Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vpc_Message");
                Onvpc_MessageChanged();
            }
        }
        private global::System.String _vpc_Message;
        partial void Onvpc_MessageChanging(global::System.String value);
        partial void Onvpc_MessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modifed_date
        {
            get
            {
                return _modifed_date;
            }
            set
            {
                Onmodifed_dateChanging(value);
                ReportPropertyChanging("modifed_date");
                _modifed_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifed_date");
                Onmodifed_dateChanged();
            }
        }
        private global::System.DateTime _modifed_date;
        partial void Onmodifed_dateChanging(global::System.DateTime value);
        partial void Onmodifed_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuatarPayemntModel", Name="TBLQU_PAYMENTMASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_PAYMENTMASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_PAYMENTMASTER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="isBlocked">Initial value of the IsBlocked property.</param>
        public static TBLQU_PAYMENTMASTER CreateTBLQU_PAYMENTMASTER(global::System.Int32 id, global::System.String amount, global::System.Boolean isBlocked)
        {
            TBLQU_PAYMENTMASTER tBLQU_PAYMENTMASTER = new TBLQU_PAYMENTMASTER();
            tBLQU_PAYMENTMASTER.ID = id;
            tBLQU_PAYMENTMASTER.Amount = amount;
            tBLQU_PAYMENTMASTER.IsBlocked = isBlocked;
            return tBLQU_PAYMENTMASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.String _ClientID;
        partial void OnClientIDChanging(global::System.String value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookingRef
        {
            get
            {
                return _BookingRef;
            }
            set
            {
                OnBookingRefChanging(value);
                ReportPropertyChanging("BookingRef");
                _BookingRef = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BookingRef");
                OnBookingRefChanged();
            }
        }
        private global::System.String _BookingRef;
        partial void OnBookingRefChanging(global::System.String value);
        partial void OnBookingRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PackageName
        {
            get
            {
                return _PackageName;
            }
            set
            {
                OnPackageNameChanging(value);
                ReportPropertyChanging("PackageName");
                _PackageName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PackageName");
                OnPackageNameChanged();
            }
        }
        private global::System.String _PackageName;
        partial void OnPackageNameChanging(global::System.String value);
        partial void OnPackageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.String _Amount;
        partial void OnAmountChanging(global::System.String value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Var_Status
        {
            get
            {
                return _Var_Status;
            }
            set
            {
                OnVar_StatusChanging(value);
                ReportPropertyChanging("Var_Status");
                _Var_Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Var_Status");
                OnVar_StatusChanged();
            }
        }
        private global::System.String _Var_Status;
        partial void OnVar_StatusChanging(global::System.String value);
        partial void OnVar_StatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String payment_id
        {
            get
            {
                return _payment_id;
            }
            set
            {
                Onpayment_idChanging(value);
                ReportPropertyChanging("payment_id");
                _payment_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("payment_id");
                Onpayment_idChanged();
            }
        }
        private global::System.String _payment_id;
        partial void Onpayment_idChanging(global::System.String value);
        partial void Onpayment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String payment_token
        {
            get
            {
                return _payment_token;
            }
            set
            {
                Onpayment_tokenChanging(value);
                ReportPropertyChanging("payment_token");
                _payment_token = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("payment_token");
                Onpayment_tokenChanged();
            }
        }
        private global::System.String _payment_token;
        partial void Onpayment_tokenChanging(global::System.String value);
        partial void Onpayment_tokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_date;
        partial void Oncreated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifed_date
        {
            get
            {
                return _modifed_date;
            }
            set
            {
                Onmodifed_dateChanging(value);
                ReportPropertyChanging("modifed_date");
                _modifed_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifed_date");
                Onmodifed_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifed_date;
        partial void Onmodifed_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodifed_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String booked_by
        {
            get
            {
                return _booked_by;
            }
            set
            {
                Onbooked_byChanging(value);
                ReportPropertyChanging("booked_by");
                _booked_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("booked_by");
                Onbooked_byChanged();
            }
        }
        private global::System.String _booked_by;
        partial void Onbooked_byChanging(global::System.String value);
        partial void Onbooked_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String currencyrate
        {
            get
            {
                return _currencyrate;
            }
            set
            {
                OncurrencyrateChanging(value);
                ReportPropertyChanging("currencyrate");
                _currencyrate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("currencyrate");
                OncurrencyrateChanged();
            }
        }
        private global::System.String _currencyrate;
        partial void OncurrencyrateChanging(global::System.String value);
        partial void OncurrencyrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentDate
        {
            get
            {
                return _PaymentDate;
            }
            set
            {
                OnPaymentDateChanging(value);
                ReportPropertyChanging("PaymentDate");
                _PaymentDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaymentDate");
                OnPaymentDateChanged();
            }
        }
        private global::System.String _PaymentDate;
        partial void OnPaymentDateChanging(global::System.String value);
        partial void OnPaymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TermAndCondition
        {
            get
            {
                return _TermAndCondition;
            }
            set
            {
                OnTermAndConditionChanging(value);
                ReportPropertyChanging("TermAndCondition");
                _TermAndCondition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TermAndCondition");
                OnTermAndConditionChanged();
            }
        }
        private Nullable<global::System.Boolean> _TermAndCondition;
        partial void OnTermAndConditionChanging(Nullable<global::System.Boolean> value);
        partial void OnTermAndConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Discription
        {
            get
            {
                return _Discription;
            }
            set
            {
                OnDiscriptionChanging(value);
                ReportPropertyChanging("Discription");
                _Discription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Discription");
                OnDiscriptionChanged();
            }
        }
        private global::System.String _Discription;
        partial void OnDiscriptionChanging(global::System.String value);
        partial void OnDiscriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FailedAttempt
        {
            get
            {
                return _FailedAttempt;
            }
            set
            {
                OnFailedAttemptChanging(value);
                ReportPropertyChanging("FailedAttempt");
                _FailedAttempt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedAttempt");
                OnFailedAttemptChanged();
            }
        }
        private Nullable<global::System.Int32> _FailedAttempt;
        partial void OnFailedAttemptChanging(Nullable<global::System.Int32> value);
        partial void OnFailedAttemptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FailedAttemptLimit
        {
            get
            {
                return _FailedAttemptLimit;
            }
            set
            {
                OnFailedAttemptLimitChanging(value);
                ReportPropertyChanging("FailedAttemptLimit");
                _FailedAttemptLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedAttemptLimit");
                OnFailedAttemptLimitChanged();
            }
        }
        private Nullable<global::System.Int32> _FailedAttemptLimit;
        partial void OnFailedAttemptLimitChanging(Nullable<global::System.Int32> value);
        partial void OnFailedAttemptLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsBlocked
        {
            get
            {
                return _IsBlocked;
            }
            set
            {
                OnIsBlockedChanging(value);
                ReportPropertyChanging("IsBlocked");
                _IsBlocked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBlocked");
                OnIsBlockedChanged();
            }
        }
        private global::System.Boolean _IsBlocked;
        partial void OnIsBlockedChanging(global::System.Boolean value);
        partial void OnIsBlockedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuatarPayemntModel", Name="TBLQU_PAYMENTRate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_PAYMENTRate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_PAYMENTRate object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="currency_From">Initial value of the Currency_From property.</param>
        /// <param name="currency_to">Initial value of the Currency_to property.</param>
        /// <param name="rate">Initial value of the rate property.</param>
        /// <param name="modifie_date">Initial value of the modifie_date property.</param>
        public static TBLQU_PAYMENTRate CreateTBLQU_PAYMENTRate(global::System.Int32 id, global::System.String currency_From, global::System.String currency_to, global::System.String rate, global::System.DateTime modifie_date)
        {
            TBLQU_PAYMENTRate tBLQU_PAYMENTRate = new TBLQU_PAYMENTRate();
            tBLQU_PAYMENTRate.ID = id;
            tBLQU_PAYMENTRate.Currency_From = currency_From;
            tBLQU_PAYMENTRate.Currency_to = currency_to;
            tBLQU_PAYMENTRate.rate = rate;
            tBLQU_PAYMENTRate.modifie_date = modifie_date;
            return tBLQU_PAYMENTRate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency_From
        {
            get
            {
                return _Currency_From;
            }
            set
            {
                if (_Currency_From != value)
                {
                    OnCurrency_FromChanging(value);
                    ReportPropertyChanging("Currency_From");
                    _Currency_From = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Currency_From");
                    OnCurrency_FromChanged();
                }
            }
        }
        private global::System.String _Currency_From;
        partial void OnCurrency_FromChanging(global::System.String value);
        partial void OnCurrency_FromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency_to
        {
            get
            {
                return _Currency_to;
            }
            set
            {
                OnCurrency_toChanging(value);
                ReportPropertyChanging("Currency_to");
                _Currency_to = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Currency_to");
                OnCurrency_toChanged();
            }
        }
        private global::System.String _Currency_to;
        partial void OnCurrency_toChanging(global::System.String value);
        partial void OnCurrency_toChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rate
        {
            get
            {
                return _rate;
            }
            set
            {
                OnrateChanging(value);
                ReportPropertyChanging("rate");
                _rate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rate");
                OnrateChanged();
            }
        }
        private global::System.String _rate;
        partial void OnrateChanging(global::System.String value);
        partial void OnrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modifie_date
        {
            get
            {
                return _modifie_date;
            }
            set
            {
                Onmodifie_dateChanging(value);
                ReportPropertyChanging("modifie_date");
                _modifie_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifie_date");
                Onmodifie_dateChanged();
            }
        }
        private global::System.DateTime _modifie_date;
        partial void Onmodifie_dateChanging(global::System.DateTime value);
        partial void Onmodifie_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuatarPayemntModel", Name="TBLQU_User_Master")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_User_Master : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_User_Master object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        public static TBLQU_User_Master CreateTBLQU_User_Master(global::System.Int32 id, global::System.String userid)
        {
            TBLQU_User_Master tBLQU_User_Master = new TBLQU_User_Master();
            tBLQU_User_Master.id = id;
            tBLQU_User_Master.userid = userid;
            return tBLQU_User_Master;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailid
        {
            get
            {
                return _emailid;
            }
            set
            {
                OnemailidChanging(value);
                ReportPropertyChanging("emailid");
                _emailid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emailid");
                OnemailidChanged();
            }
        }
        private global::System.String _emailid;
        partial void OnemailidChanging(global::System.String value);
        partial void OnemailidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mobileno
        {
            get
            {
                return _mobileno;
            }
            set
            {
                OnmobilenoChanging(value);
                ReportPropertyChanging("mobileno");
                _mobileno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobileno");
                OnmobilenoChanged();
            }
        }
        private Nullable<global::System.Int32> _mobileno;
        partial void OnmobilenoChanging(Nullable<global::System.Int32> value);
        partial void OnmobilenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_type
        {
            get
            {
                return _user_type;
            }
            set
            {
                Onuser_typeChanging(value);
                ReportPropertyChanging("user_type");
                _user_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_type");
                Onuser_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _user_type;
        partial void Onuser_typeChanging(Nullable<global::System.Int32> value);
        partial void Onuser_typeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuatarPayemntModel", Name="TBLQU_UserLocation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_UserLocation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_UserLocation object.
        /// </summary>
        /// <param name="userLocationPK">Initial value of the UserLocationPK property.</param>
        public static TBLQU_UserLocation CreateTBLQU_UserLocation(global::System.Int32 userLocationPK)
        {
            TBLQU_UserLocation tBLQU_UserLocation = new TBLQU_UserLocation();
            tBLQU_UserLocation.UserLocationPK = userLocationPK;
            return tBLQU_UserLocation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookingRef
        {
            get
            {
                return _BookingRef;
            }
            set
            {
                OnBookingRefChanging(value);
                ReportPropertyChanging("BookingRef");
                _BookingRef = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BookingRef");
                OnBookingRefChanged();
            }
        }
        private global::System.String _BookingRef;
        partial void OnBookingRefChanging(global::System.String value);
        partial void OnBookingRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryCode
        {
            get
            {
                return _CountryCode;
            }
            set
            {
                OnCountryCodeChanging(value);
                ReportPropertyChanging("CountryCode");
                _CountryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryCode");
                OnCountryCodeChanged();
            }
        }
        private global::System.String _CountryCode;
        partial void OnCountryCodeChanging(global::System.String value);
        partial void OnCountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryName
        {
            get
            {
                return _CountryName;
            }
            set
            {
                OnCountryNameChanging(value);
                ReportPropertyChanging("CountryName");
                _CountryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryName");
                OnCountryNameChanged();
            }
        }
        private global::System.String _CountryName;
        partial void OnCountryNameChanging(global::System.String value);
        partial void OnCountryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionCode
        {
            get
            {
                return _RegionCode;
            }
            set
            {
                OnRegionCodeChanging(value);
                ReportPropertyChanging("RegionCode");
                _RegionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegionCode");
                OnRegionCodeChanged();
            }
        }
        private global::System.String _RegionCode;
        partial void OnRegionCodeChanging(global::System.String value);
        partial void OnRegionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionName
        {
            get
            {
                return _RegionName;
            }
            set
            {
                OnRegionNameChanging(value);
                ReportPropertyChanging("RegionName");
                _RegionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegionName");
                OnRegionNameChanged();
            }
        }
        private global::System.String _RegionName;
        partial void OnRegionNameChanging(global::System.String value);
        partial void OnRegionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeZone
        {
            get
            {
                return _TimeZone;
            }
            set
            {
                OnTimeZoneChanging(value);
                ReportPropertyChanging("TimeZone");
                _TimeZone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeZone");
                OnTimeZoneChanged();
            }
        }
        private global::System.String _TimeZone;
        partial void OnTimeZoneChanging(global::System.String value);
        partial void OnTimeZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserLocationPK
        {
            get
            {
                return _UserLocationPK;
            }
            set
            {
                if (_UserLocationPK != value)
                {
                    OnUserLocationPKChanging(value);
                    ReportPropertyChanging("UserLocationPK");
                    _UserLocationPK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserLocationPK");
                    OnUserLocationPKChanged();
                }
            }
        }
        private global::System.Int32 _UserLocationPK;
        partial void OnUserLocationPKChanging(global::System.Int32 value);
        partial void OnUserLocationPKChanged();

        #endregion

    
    }

    #endregion

    
}
