//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Qa_Payment
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QUPAYMENTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QUPAYMENTEntities object using the connection string found in the 'QUPAYMENTEntities' section of the application configuration file.
        /// </summary>
        public QUPAYMENTEntities() : base("name=QUPAYMENTEntities", "QUPAYMENTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QUPAYMENTEntities object.
        /// </summary>
        public QUPAYMENTEntities(string connectionString) : base(connectionString, "QUPAYMENTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QUPAYMENTEntities object.
        /// </summary>
        public QUPAYMENTEntities(EntityConnection connection) : base(connection, "QUPAYMENTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_PAYMENTMASTER> TBLQU_PAYMENTMASTER
        {
            get
            {
                if ((_TBLQU_PAYMENTMASTER == null))
                {
                    _TBLQU_PAYMENTMASTER = base.CreateObjectSet<TBLQU_PAYMENTMASTER>("TBLQU_PAYMENTMASTER");
                }
                return _TBLQU_PAYMENTMASTER;
            }
        }
        private ObjectSet<TBLQU_PAYMENTMASTER> _TBLQU_PAYMENTMASTER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_User_Master> TBLQU_User_Master
        {
            get
            {
                if ((_TBLQU_User_Master == null))
                {
                    _TBLQU_User_Master = base.CreateObjectSet<TBLQU_User_Master>("TBLQU_User_Master");
                }
                return _TBLQU_User_Master;
            }
        }
        private ObjectSet<TBLQU_User_Master> _TBLQU_User_Master;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBLQU_CLIENTMASTER> TBLQU_CLIENTMASTER
        {
            get
            {
                if ((_TBLQU_CLIENTMASTER == null))
                {
                    _TBLQU_CLIENTMASTER = base.CreateObjectSet<TBLQU_CLIENTMASTER>("TBLQU_CLIENTMASTER");
                }
                return _TBLQU_CLIENTMASTER;
            }
        }
        private ObjectSet<TBLQU_CLIENTMASTER> _TBLQU_CLIENTMASTER;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_PAYMENTMASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_PAYMENTMASTER(TBLQU_PAYMENTMASTER tBLQU_PAYMENTMASTER)
        {
            base.AddObject("TBLQU_PAYMENTMASTER", tBLQU_PAYMENTMASTER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_User_Master EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_User_Master(TBLQU_User_Master tBLQU_User_Master)
        {
            base.AddObject("TBLQU_User_Master", tBLQU_User_Master);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBLQU_CLIENTMASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBLQU_CLIENTMASTER(TBLQU_CLIENTMASTER tBLQU_CLIENTMASTER)
        {
            base.AddObject("TBLQU_CLIENTMASTER", tBLQU_CLIENTMASTER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUPAYMENTModel", Name="TBLQU_CLIENTMASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_CLIENTMASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_CLIENTMASTER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="mobileNo">Initial value of the MobileNo property.</param>
        /// <param name="emailID">Initial value of the EmailID property.</param>
        public static TBLQU_CLIENTMASTER CreateTBLQU_CLIENTMASTER(global::System.Int32 id, global::System.Decimal mobileNo, global::System.String emailID)
        {
            TBLQU_CLIENTMASTER tBLQU_CLIENTMASTER = new TBLQU_CLIENTMASTER();
            tBLQU_CLIENTMASTER.ID = id;
            tBLQU_CLIENTMASTER.MobileNo = mobileNo;
            tBLQU_CLIENTMASTER.EmailID = emailID;
            return tBLQU_CLIENTMASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.String _ClientID;
        partial void OnClientIDChanging(global::System.String value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientfirstName
        {
            get
            {
                return _ClientfirstName;
            }
            set
            {
                OnClientfirstNameChanging(value);
                ReportPropertyChanging("ClientfirstName");
                _ClientfirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientfirstName");
                OnClientfirstNameChanged();
            }
        }
        private global::System.String _ClientfirstName;
        partial void OnClientfirstNameChanging(global::System.String value);
        partial void OnClientfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientLastName
        {
            get
            {
                return _ClientLastName;
            }
            set
            {
                OnClientLastNameChanging(value);
                ReportPropertyChanging("ClientLastName");
                _ClientLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientLastName");
                OnClientLastNameChanged();
            }
        }
        private global::System.String _ClientLastName;
        partial void OnClientLastNameChanging(global::System.String value);
        partial void OnClientLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private Nullable<global::System.Decimal> _PhoneNo;
        partial void OnPhoneNoChanging(Nullable<global::System.Decimal> value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MobileNo
        {
            get
            {
                return _MobileNo;
            }
            set
            {
                OnMobileNoChanging(value);
                ReportPropertyChanging("MobileNo");
                _MobileNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MobileNo");
                OnMobileNoChanged();
            }
        }
        private global::System.Decimal _MobileNo;
        partial void OnMobileNoChanging(global::System.Decimal value);
        partial void OnMobileNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUPAYMENTModel", Name="TBLQU_PAYMENTMASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_PAYMENTMASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_PAYMENTMASTER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="clientID">Initial value of the ClientID property.</param>
        /// <param name="bookingRef">Initial value of the BookingRef property.</param>
        /// <param name="packageName">Initial value of the PackageName property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="currency">Initial value of the Currency property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="var_Status">Initial value of the Var_Status property.</param>
        /// <param name="payment_id">Initial value of the payment_id property.</param>
        /// <param name="payment_token">Initial value of the payment_token property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        /// <param name="modifed_date">Initial value of the modifed_date property.</param>
        public static TBLQU_PAYMENTMASTER CreateTBLQU_PAYMENTMASTER(global::System.Int32 id, global::System.String clientID, global::System.String bookingRef, global::System.String packageName, global::System.Decimal amount, global::System.String currency, global::System.Int32 status, global::System.String var_Status, global::System.String payment_id, global::System.String payment_token, global::System.DateTime created_date, global::System.DateTime modifed_date)
        {
            TBLQU_PAYMENTMASTER tBLQU_PAYMENTMASTER = new TBLQU_PAYMENTMASTER();
            tBLQU_PAYMENTMASTER.ID = id;
            tBLQU_PAYMENTMASTER.ClientID = clientID;
            tBLQU_PAYMENTMASTER.BookingRef = bookingRef;
            tBLQU_PAYMENTMASTER.PackageName = packageName;
            tBLQU_PAYMENTMASTER.Amount = amount;
            tBLQU_PAYMENTMASTER.Currency = currency;
            tBLQU_PAYMENTMASTER.Status = status;
            tBLQU_PAYMENTMASTER.Var_Status = var_Status;
            tBLQU_PAYMENTMASTER.payment_id = payment_id;
            tBLQU_PAYMENTMASTER.payment_token = payment_token;
            tBLQU_PAYMENTMASTER.created_date = created_date;
            tBLQU_PAYMENTMASTER.modifed_date = modifed_date;
            return tBLQU_PAYMENTMASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.String _ClientID;
        partial void OnClientIDChanging(global::System.String value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BookingRef
        {
            get
            {
                return _BookingRef;
            }
            set
            {
                if (_BookingRef != value)
                {
                    OnBookingRefChanging(value);
                    ReportPropertyChanging("BookingRef");
                    _BookingRef = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BookingRef");
                    OnBookingRefChanged();
                }
            }
        }
        private global::System.String _BookingRef;
        partial void OnBookingRefChanging(global::System.String value);
        partial void OnBookingRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackageName
        {
            get
            {
                return _PackageName;
            }
            set
            {
                OnPackageNameChanging(value);
                ReportPropertyChanging("PackageName");
                _PackageName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PackageName");
                OnPackageNameChanged();
            }
        }
        private global::System.String _PackageName;
        partial void OnPackageNameChanging(global::System.String value);
        partial void OnPackageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Var_Status
        {
            get
            {
                return _Var_Status;
            }
            set
            {
                OnVar_StatusChanging(value);
                ReportPropertyChanging("Var_Status");
                _Var_Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Var_Status");
                OnVar_StatusChanged();
            }
        }
        private global::System.String _Var_Status;
        partial void OnVar_StatusChanging(global::System.String value);
        partial void OnVar_StatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String payment_id
        {
            get
            {
                return _payment_id;
            }
            set
            {
                Onpayment_idChanging(value);
                ReportPropertyChanging("payment_id");
                _payment_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("payment_id");
                Onpayment_idChanged();
            }
        }
        private global::System.String _payment_id;
        partial void Onpayment_idChanging(global::System.String value);
        partial void Onpayment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String payment_token
        {
            get
            {
                return _payment_token;
            }
            set
            {
                Onpayment_tokenChanging(value);
                ReportPropertyChanging("payment_token");
                _payment_token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("payment_token");
                Onpayment_tokenChanged();
            }
        }
        private global::System.String _payment_token;
        partial void Onpayment_tokenChanging(global::System.String value);
        partial void Onpayment_tokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modifed_date
        {
            get
            {
                return _modifed_date;
            }
            set
            {
                Onmodifed_dateChanging(value);
                ReportPropertyChanging("modifed_date");
                _modifed_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifed_date");
                Onmodifed_dateChanged();
            }
        }
        private global::System.DateTime _modifed_date;
        partial void Onmodifed_dateChanging(global::System.DateTime value);
        partial void Onmodifed_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String booked_by
        {
            get
            {
                return _booked_by;
            }
            set
            {
                Onbooked_byChanging(value);
                ReportPropertyChanging("booked_by");
                _booked_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("booked_by");
                Onbooked_byChanged();
            }
        }
        private global::System.String _booked_by;
        partial void Onbooked_byChanging(global::System.String value);
        partial void Onbooked_byChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUPAYMENTModel", Name="TBLQU_User_Master")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBLQU_User_Master : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBLQU_User_Master object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        public static TBLQU_User_Master CreateTBLQU_User_Master(global::System.Int32 id, global::System.String userid)
        {
            TBLQU_User_Master tBLQU_User_Master = new TBLQU_User_Master();
            tBLQU_User_Master.id = id;
            tBLQU_User_Master.userid = userid;
            return tBLQU_User_Master;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailid
        {
            get
            {
                return _emailid;
            }
            set
            {
                OnemailidChanging(value);
                ReportPropertyChanging("emailid");
                _emailid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emailid");
                OnemailidChanged();
            }
        }
        private global::System.String _emailid;
        partial void OnemailidChanging(global::System.String value);
        partial void OnemailidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mobileno
        {
            get
            {
                return _mobileno;
            }
            set
            {
                OnmobilenoChanging(value);
                ReportPropertyChanging("mobileno");
                _mobileno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobileno");
                OnmobilenoChanged();
            }
        }
        private Nullable<global::System.Int32> _mobileno;
        partial void OnmobilenoChanging(Nullable<global::System.Int32> value);
        partial void OnmobilenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_type
        {
            get
            {
                return _user_type;
            }
            set
            {
                Onuser_typeChanging(value);
                ReportPropertyChanging("user_type");
                _user_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_type");
                Onuser_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _user_type;
        partial void Onuser_typeChanging(Nullable<global::System.Int32> value);
        partial void Onuser_typeChanged();

        #endregion

    
    }

    #endregion

    
}
